services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - ./order-service/migrations:/docker-entrypoint-initdb.d

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"
    volumes:
      - ./payment-service/migrations:/docker-entrypoint-initdb.d

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: on-failure
    depends_on:
      - payment-db
      - rabbitmq
    ports:
      - "8081:8081"
      - "50051:50051"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${PAYMENT_DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}

  order-service:
    build: ./order-service
    container_name: order-service
    restart: on-failure
    depends_on:
      - order-db
      - payment-service
      - redis
    ports:
      - "8080:8080"
      - "50052:50052"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${ORDER_DATABASE_URL}
      PAYMENT_GRPC_ADDR: ${PAYMENT_GRPC_ADDR}
      REDIS_ADDR: ${REDIS_ADDR}
      ORDER_CACHE_TTL_SECONDS: ${ORDER_CACHE_TTL_SECONDS}

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: on-failure
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      REDIS_ADDR: ${REDIS_ADDR}
      PROVIDER_MODE: ${PROVIDER_MODE}
      NOTIFICATION_MAX_RETRIES: ${NOTIFICATION_MAX_RETRIES}
      NOTIFICATION_BACKOFF_SECONDS: ${NOTIFICATION_BACKOFF_SECONDS}